[package]
name = "crypto"
version = "0.1.0"
authors = ["Christopher Tobias <ctobias@gmx.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Cryptography Primitives for Cryptonote"

[dependencies]
arrayref = "0.3"
curve25519-dalek = "1"
hex = "0.3"
rand = "0.6"
sha3 = "0.8"
